version: '3'

services:
  web:
    image: nginx
    volumes:
      # ホスト側のパス:コンテナ側のパス
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx
      # アセットを反映させる。
      - ./public:/app/public
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build: .
    # 以前のプロセスを削除してからrails s
    # rails sした時にURL(http://0.0.0.0:3000)にアクセス=localhost:3000
    # -p 3000：サーバ起動時のポート番号を3000に設定 -b '0.0.0.0'：ポート番号3000をIPアドレス0.0.0.0と関連付け
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      # ホストPCのアプリケーションファイルをマウント
      - .:/app
    ports:
      # localhostのポート番号3000でアクセスできるようにする
      - "3000:3000"
    # db起動後にappが起動（依存関係）
    depends_on:
      - db

  db:
    image: mysql:5.6
    volumes:
      # マウントを利用したデータの永続化
      # - ./mysql:/var/lib/mysql
      # 名前付きボリュームを利用したデータの永続化
      - mysql_data:/var/lib/mysql
      # 作成したスクリプトをコンテナ上で読み取れるようにするためバインドマウントを追加
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    # v8.0用の設定
    # MySQL 8標準のcaching_sha2_passwordの認証方式だとDBへ接続できないため、認証方式を8系以前のものへ変更
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'rails_app_dev'

# データボリューム名を設定
volumes:
  mysql_data: